### ISSUE TITLE
exception handling for parser ValueError should not write all bad lines out to logs

### ISSUE THREAD

**Issue by dehowell** [klbostee/dumbo#12]
If a parser is accidentally used on the wrong type of data file (a pretty common mistake among the analysts I'm supporting with Dumbo), the entire contents of the input file get dumped into the job logs. 

I've seen this bring nodes down repeatedly, when the partition holding the log files gets completely filled up. Parsers are very useful, but I think it would be better if bad values just incremented a counter.

**Comment by klbostee** [comment]
Good point and shouldn't be hard to fix. I'll try to write a patch soonish, but feel free to beat me to it.

**Comment by klbostee** [comment]
Fixed by 55f77cced62f371052e83cbec22ba244fa5d9bff
