### ISSUE TITLE
equality test between join keys should be customizable

### ISSUE THREAD

**Issue by dehowell** [klbostee/dumbo#13]
Sometimes it's handy to have the equality test between join keys be something other than strict equality; moving the key equality test into its own method would make it easier for subclasses of JoinReducer to customize.

Also, by putting the key_check method can be defined in JoinCombiner to always return True, in which case it's no longer necessary to duplicate the logic in the **call** method in both JoinCombiner and JoinReducer.

I'm issuing a pull request with my patch.

**Comment by klbostee** [comment]
Nice enhancement, David. The additional function call might have a slight performance impact, but it should be minimal (if not negligible) and the benefits seem to be worth it.

I think we should be able to come up with a better name than "key_check" though. What it really does is determine if the secondary method should be blocked or not, so maybe something like "if not secondary_blocked(key.body):"? It's not that important I guess, but especially if the plan is to let people override it then it would make sense to use a clear name.

**Comment by dehowell** [comment]
I agree, key_check is not the best name, and secondary_blocked seems good. I'll update the names in my fork.
