### ISSUE TITLE
dumbo fails to find hadoop streaming jar

### ISSUE THREAD

**Issue by shaneaevans** [klbostee/dumbo#14]
After upgrading hadoop (to hadoop-0.20-0.20.2+320-1.noarch using cloudera's yum repo), dumbo no longer finds the hadoop streaming jar.

It seems that the jar filename has changed to:
hadoop-streaming-0.20.2+320.jar
which is not matched by the regular expression in util.py:
re.compile(r'hadoop.*%s.jar' % name)

**Comment by klbostee** [comment]
Closed by d3696292f5ebf1c80dc87f7bf294953a35f88bef
