### ISSUE TITLE
dumbo cat silently fails when JobHistory logging is enabled

### ISSUE THREAD

**Issue by emf** [klbostee/dumbo#19]
Causes frustration with new users that don't know why it's mysteriously failing and haven't figured out either of the workarounds yet.

proposed patch included.. perhaps not the best solution, but better than failing silently.

<pre><verbatim>
diff --git a/dumbo/backends/streaming.py b/dumbo/backends/streaming.py
index f71e611..7755fbe 100644
--- a/dumbo/backends/streaming.py
+++ b/dumbo/backends/streaming.py
@@ -230,6 +230,8 @@ class StreamingFileSystem(FileSystem):
                 subpaths = [path]
             ls.close()
             for subpath in subpaths:
+                if subpath.endswith("/_logs"):
+                    continue
                 dumptb = os.popen('%s %s/bin/hadoop jar %s dumptb %s 2> /dev/null'
                                   % (hadenv, self.hadoop, streamingjar, subpath))
                 ascodeopt = getopt(opts, 'ascode')
</verbatim></pre>

**Comment by klbostee** [comment]
bugfix contributed by Erik Fichtner (closed by 550528bbeaa3d5c484869b0918fff3a2f86823a4)
