### ISSUE TITLE
Outputting bytes directly on Hadoop is not possible

### ISSUE THREAD

**Issue by klbostee** [klbostee/dumbo#22]
As Python strings are mapped to typedbytes (UTF-8) strings, it isn't currently possible to output binary data directly without any intermediate transformations of the bytes.

See also https://github.com/tims/lasthbase/issues#issue/3 for more info.

**Comment by aripollak** [comment]
Is this the same as #32?

**Comment by klbostee** [comment]
Sort of, but this is actually fixed by https://github.com/klbostee/typedbytes/commit/976a168f50c2ba47dfa415b5d9a45bd845f23b89 now I think. Outputting typedbytes.Bytes objects should allow the outputting of bytes without any unwanted transformations...
