### ISSUE TITLE
Two error handling bugs in core.py

### ISSUE THREAD

**Issue by andrewclegg** [klbostee/dumbo#30]
First one's just a typo: on line 209, it has 'sdterr' instead of 'stderr'.

The second one might not be a bug but it looks a bit suspect to me :-) On line 197, program.start() is called regardless of whether starter(program) succeeded or failed.

Shouldn't it test this first, and not try to start the job if the starter failed? e.g.

```
retval = program.start() if status == 0 else status
```

**Comment by klbostee** [comment]
two small fixes (closed by 1d634330b0761c508cb187c1db2bb34a16c78903)
