### ISSUE TITLE
reducers for outputting raw binary files, tokyo cabinet dbs or constant dbs 

### ISSUE THREAD

**Issue by klbostee** [klbostee/dumbo#32]
See recent commits on https://github.com/dangra/dumbo

**Comment by klbostee** [comment]
Had a quick look at the code and it looks great to me. Definitely some very nice contributions, thanks!

The "dumbo.contrib" package seems a fair enough place to put these reducers, but I wouldn't mind converting "dumbo.lib" in a package either as long as we put everything it already contains now (either directly or indirectly via imports) in "dumbo/lib/**init**.py" to preserve backwards compatibility. I might even prefer the latter, unless I'm overlooking some potential downsides?

I do have one comment after a quick glance through your code though: The tests you added should probably go in "tests/" instead of "dumbo/contrib".

**Comment by dangra** [comment]
My time to apology for delayed answer, finally got some free time to work on this, check recent commits tagged by GH-32 in my fork. thanks!

**Comment by klbostee** [comment]
Merged in 0094bdb37ac697523074a5a9d20c01bf49665ba5. Thanks Daniel!
