### ISSUE TITLE
Override or disable config files

### ISSUE THREAD

**Issue by andrewclegg** [klbostee/dumbo#33]
It'd be really useful to have a command-line switch to say "don't read any config files" or "read this specific config file instead of the default ones".

That way, you could run dumbo from a virtualenv or buildout without worrying that eggs, jars etc. specified in dumbo.conf or .dumborc would sneak in.

**Comment by klbostee** [comment]
Agreed. This is kind of related to #29 too.

I guess the easiest way of doing this would be to always pass the "opts" list to the "dumbo.util.configopts" function and vary its behavior based on a "config" option or so. While we're at it, It might make sense to rethink the options handling a bit and do a more involved refactor though -- it's one of the (several) implementation aspects of Dumbo that evolved very fast and organically and consequently isn't as clean and elegant as it could be.

Anyway, patches and/or pull requests are welcome.. :)

**Comment by andrewclegg** [comment]
Cool, if you think it's a good plan I'll see if I can knock up a patched version at some point.
