### ISSUE TITLE
document why anyone should use this

### ISSUE THREAD

**Issue by Dieterbe** [klbostee/dumbo#34]
Hi, the readme says basically "Python module that allows you to easily write and run Hadoop programs", and points the wiki, which contains some config files and sample programs.

If you really want to attract users, you should mention more explicitly why users should use this, rather then writing their own python programs for the streaming api.

AFAICT, dumbo provides:
- wrapping i/o (streaming api stdin/stdout) to function arguments and return values
- something to make sure reducers are run with a constant key, whereas with the streaming api reducers can get key/value pairs with different keys.

that seems to be it, from a quick glance.
If you recommend users to add this 2500-lines-of-python dependency, you should imho justify it more.

**Comment by klbostee** [comment]
I guess we could explain the features/benefits better. Will give it a go whenever I can find some time for it...

**Comment by klbostee** [comment]
So I added a bit more info to http://last.fm/dumbo, hope that clarifies things somewhat...

**Comment by Dieterbe** [comment]
Thanks, that's better indeed.
Personally though, I think it sounds quite like a sales pitch, and not aimed at developers.  I think if you want to attract developers, you should focus more on technical design details, and technical benefits.  
for example:
- dumbo is a python api on top of the hadoop streaming api, using typed bytes instead of plaintext to increase performance.
- however, you're still free to override input/output formats as you please
- it also comes with boilerplate code that takes care of foo and bar, so that instead of doing x as you need to when just using the streaming api, you can now do y

I hope my contributions are somewhat useful.  What I'm trying to say is, I'm a python developer currently using the streaming api, and if you want to convince me to try out dumbo, you should speak developer language and tell me why I should try dumbo.  A sentence like "Dumbo also provides more than enough boilerplate functionality and additional features to give (directly) using Hadoop Streaming a run for its money. " is not only just sales talk that offers no additional value, it's actually text that gets in my way when I'm trying to find real benefits for me in the description text.
