### ISSUE TITLE
dumbo with virtualenv

### ISSUE THREAD

**Issue by oddskool** [klbostee/dumbo#41]
Hi there,

I'm having trouble making dumbo work with virtualenv. 

My setting is a hadoop grid running cloudera cdh3b3 on debian lenny (yes I know it's old). In order to run a decent, fixed version of python I have a virtualenv with python2.6 and dumbo installed into it.

When running in local mode a simple example (ipcount), everything is fine.

But when I try to run in grid mode, I get this error:
"""
(0.0.5)ediemert@bom-dev-hadn9:~/sources/scratch/dumbo$ dumbo start count.py -input /benchmark/data/dbpedia/long_a
bstracts_en.nt -output wcounts -hadoop /usr/lib/hadoop/ 
EXEC: HADOOP_CLASSPATH=":$HADOOP_CLASSPATH" /usr/lib/hadoop//bin/hadoop jar /usr/lib/hadoop/contrib/streaming/hadoop-streaming-0.20.2+737.jar -input '/benchmark/data/dbpedia/long_abstracts_en.nt' -output 'wcounts' -cmdenv 'dumbo_mrbase_class=dumbo.backends.common.MapRedBase' -cmdenv 'dumbo_jk_class=dumbo.backends.common.JoinKey' -cmdenv 'dumbo_runinfo_class=dumbo.backends.streaming.StreamingRunInfo' -mapper 'python -m count map 0 262144000' -reducer 'python -m count red 0 262144000' -jobconf 'stream.map.input=typedbytes' -jobconf 'stream.reduce.input=typedbytes' -jobconf 'stream.map.output=typedbytes' -jobconf 'stream.reduce.output=typedbytes' -jobconf 'mapred.job.name=count.py (1/1)' -inputformat 'org.apache.hadoop.streaming.AutoInputFormat' -outputformat 'org.apache.hadoop.mapred.SequenceFileOutputFormat' -cmdenv 'PYTHONPATH=common.pyc' -file '/home/ediemert/sources/scratch/dumbo/count.py' -file '/home/sites/sci-env/0.0.5/lib/python2.6/site-packages/dumbo/backends/common.pyc' -jobconf 'tmpfiles=/home/sites/sci-env/0.0.5/lib/python2.6/site-packages/typedbytes.pyc'
11/05/23 16:02:13 WARN streaming.StreamJob: -jobconf option is deprecated, please use -D instead.
packageJobJar: [/home/ediemert/sources/scratch/dumbo/count.py, /home/sites/sci-env/0.0.5/lib/python2.6/site-packages/dumbo/backends/common.pyc, /tmp/hadoop-ediemert/hadoop-unjar5768148904382263570/] [] /tmp/streamjob6800517112258694028.jar tmpDir=null
11/05/23 16:02:13 INFO mapred.JobClient: Cleaning up the staging area hdfs://bom-dev-hann1.xxx.com/tmp/hadoop-mapred/mapred/staging/ediemert/.staging/job_201104261107_0645
11/05/23 16:02:13 ERROR streaming.StreamJob: Error launching job , bad input path : File does not exist: /home/sites/sci-env/0.0.5/lib/python2.6/site-packages/typedbytes.pyc
Streaming Command Failed!
"""

It seems to me like this error is related to my python2.6 and dumbo being executed from virtualenv.

Any ideas on how to tackle this problem ?

thansk a lot !

oddskool

**Comment by klbostee** [comment]
Both dumbo and the typedbytes module have to be installed as an egg (within the virtualenv in your case).

**Comment by oddskool** [comment]
dumbo and typedbytes _are_ installed as eggs in my virtualenv !

"""
(0.0.5)ediemert@bom-dev-hadn9:~/sources/scratch/dumbo$ python -c "import typedbytes, dumbo; print 'ok'"
ok
"""

to be fully convinced:
"""
(0.0.5)ediemert@bom-dev-hadn9:~/sources/scratch/dumbo$ ls /home/sites/sci-env/0.0.5/lib/python2.6/site-packages/dumbo\* -d
/home/sites/sci-env/0.0.5/lib/python2.6/site-packages/dumbo  /home/sites/sci-env/0.0.5/lib/python2.6/site-packages/dumbo-0.21.30-py2.6.egg-info

(0.0.5)ediemert@bom-dev-hadn9:~/sources/scratch/dumbo$ ls /home/sites/sci-env/0.0.5/lib/python2.6/site-packages/typedbytes\* -d
/home/sites/sci-env/0.0.5/lib/python2.6/site-packages/typedbytes-0.3.6-py2.6.egg-info  /home/sites/sci-env/0.0.5/lib/python2.6/site-packages/typedbytes.pyc
/home/sites/sci-env/0.0.5/lib/python2.6/site-packages/typedbytes.py
"""

**Comment by oddskool** [comment]
maybe should I switch this thread to dumbo-user ? (just found the mailing list)

**Comment by klbostee** [comment]
With "as eggs" I meant that they need to be installed as a single .egg file, which clearly isn't the case in your virtual env.

**Comment by klbostee** [comment]
And the mailing list is indeed a better place for discussing installation problems yeah.

**Comment by oddskool** [comment]
aha. by re-reading the twiki I found that I followed the normal setup (as opposed to the virtualenv specific one). 

putting it plainly for archival purposes :

$ sudo `which easy_install-2.6` dumbo

which command I typed from within the virtualenv. 

many thanks & have a nice day !

oddskool
