### ISSUE TITLE
HELP me!

### ISSUE THREAD

**Issue by cailong** [klbostee/dumbo#46]
In my task, i want use Dumbo to do this:
 the function of mapper get IP and occurrences number from server`s log.
 and the reducer function return a SQL with key(IP) and value(occurrences number)
 just like so:
       def mapper(key, value) :
             key = """get the ip for value"""
             yield key,1
       def combiner(key,value) :
             yield key,sum(value)
       def reducer(key,value) :
             yield """sql with key and value"""

how can i do?
Please forgive my bad English.
The friend from China wait for you answer!
Very Thinks!

**Comment by klbostee** [comment]
This is not the right place for asking questions. Please use the mailing list instead.

**Comment by cailong** [comment]
OK, very thanks!
