### ISSUE TITLE
Want to preserve job output

### ISSUE THREAD

**Issue by gvtech** [klbostee/dumbo#49]
Hi,

I've a program consisting of 3 jobs. 
I have 3 additer to create the job sequence and I would like to save the output of the 2nd job.
I looked to the code and saw that preoutputs option should be set to "yes" but I cannot figure out how to set it without having a error when the hadoop jobs are started.

Thank you for helping me.

**Comment by klbostee** [comment]
This is not the right place for asking questions. Please use the mailing list instead.
